### ISSUE TITLE
firefox frontend issue

### ISSUE THREAD

**Issue by vkhv** [ch1ller0/fridgefm-radio-core#316]
![Снимок экрана 2021-10-27 в 17 52 23](https://user-images.githubusercontent.com/6794386/139091128-efa711d9-8e6d-49ee-81b9-b5a0bf424da0.png)

А где у тебя фронт лежит?)
В firefox проблемы, как на маке так и на винде)

**Comment by ch1ller0** [comment]
Привет, фронт лежит отдельно, спасибо за репорт! в ближайшее время пофикшу, отпишусь сюда как будет готово

**Comment by ch1ller0** [comment]
Поправил, спасибо за ишью и спасибо что слушаешь https://fridgefm.com/ )
