### ISSUE TITLE
Suggestion: Have a way to reorder the playlist (NOT shuffle)

### ISSUE THREAD

**Issue by LaganYT** [ch1ller0/fridgefm-radio-core#326]
kinda like this:

https://www.radioking.com/on/upload/TUTOS%20V1%20MANAGER%20EN/regen-en.gif

**Comment by ch1ller0** [comment]
Hey, could you please clarify the reordering algorithm?

**Comment by LaganYT** [comment]
It is kind of like a way to drag and drop the audio files. 
[Photo Editor _ Pixlr E - free image editing tool.webm](https://user-images.githubusercontent.com/95306463/189537807-7881c03a-adb2-4329-98b6-2015e1cd3ec0.webm)
Kind of like this video ^

I hope that helps explain it.

**Comment by ch1ller0** [comment]
Thanks for the idea, however in your case the playing track changes immediately. I personally consider this logic harmful for the radio listeners. Also, there is already a method to rearrange https://github.com/ch1ller0/fridgefm-radio-core/blob/master/src/base/Playlist/methods.ts#L24 . Please consider using this one

**Comment by LaganYT** [comment]
Can you make a working version for the reorder thing on the demo main html page?
