### ISSUE TITLE
Feature: allow mounting onto the stream via an audio stream (obs but audio)

### ISSUE THREAD

**Issue by LaganYT** [ch1ller0/fridgefm-radio-core#338]
Hello,

Sorry if this sound confusing, I am wanting to be able to stream to my audio stream, like a radio, so i can start talking like it's a show. I don't want to record myself and then upload it anymore I would rather stream directly live, like a radio station.

Let me know if you want more info.

**Comment by ch1ller0** [comment]
Hey!
I believe I know what you mean. I actually have an open issue for that: https://github.com/ch1ller0/fridgefm-radio-core/issues/315
I didn't have any time to research though. Would really appreciate if you could contribute!

**Comment by LaganYT** [comment]
Ya, if I get free time I will research and see what I can do.
